### ISSUE TITLE
Document the Binie binary format 📜 

### ISSUE THREAD

**Issue by joamag** [hivesolutions/colony_print#2]
## Why

Binie is becoming an exciting format for the native printing of simple documents. Even though its format is simple, it's important to properly document its structure and rules.

## What

Create a Markdown document that defines the structure of the Binie file format, taking inspiration from the documentation of other formats.

## How

Build the document and store it in the colony-print repo.

## Inspiration

* [BESS – Best Effort Save State 1.0](https://github.com/LIJI32/SameBoy/blob/master/BESS.md)

**Comment by hugo-gomes** [comment]
Reference https://github.com/hivesolutions/colony-npapi/blob/master/src/colony_npapi/print/print_win32.h

**Comment by joamag** [comment]
@hugo-gomes I'm closing this one as done.
